### ISSUE TITLE
not able to propertly use @property decorator

### ISSUE THREAD

**Issue by razvanc87** [neovim/python-client#126] opened 2015-07-12 11:18 UTC
So I have this `self._buffer` object which is set to `None` in `__init__`. Then I have this `buffer` function decorated with the `@property` decorator. So I'm trying to open a new buffer with `nvim.command('new')` in this function and also set this buffer to `scratch` type by modifying the `options`. There are two problems:

1. when I run `UpdateRemotePlugins` these commands for opening a new buffer and setting up everything get execute... which isn't the behavior I expected
2. the command fails and the plugin doesn't get registered

Any ides? Thanks.

Oh, forgot to mention I only tried this on `python3` (I don't even care about trying to make it work for `python2`)

**Comment by bfredl** [comment] 2015-07-12 12:20
To be clear, are you talking about [this code](https://github.com/razvanc87/nvim-jupyter/blob/master/rplugin/python3/nvim_jupyter.py) (in that exact version) ?

**Comment by razvanc87** [comment] 2015-07-12 12:22
Yes, that code doesn't work at the moment because of the explained behavior...

**Comment by bfredl** [comment] 2015-07-13 15:42
I think this is not a bug. The plugin host needs to enumerate all the attributes of the plugin object, to find rpc methods, and just accessing an attribute should not cause any visible side-effect.

**Comment by razvanc87** [comment] 2015-07-13 15:48
Funny, I was just looking at this. I got around the issue by creating a method to set the buffer up on connection. But on the other hand it would be nice to have it work on the `@property` decorator... that's one of the reasons `@property` exists... to set up things. And how is this any different to having a method instead of a `@property`? Methods are attributes too... I moved the code from the `@property' function to a [new `self._set_buffer` method](https://github.com/razvanc87/nvim-jupyter/blob/master/rplugin/python3/nvim_jupyter/__init__.py#L167) and now it works.

**Comment by bfredl** [comment] 2015-07-13 16:23
Set up things internally maybe, but I don't think one should cause obserable sideeffects from just acessing an attribute. The difference is that methods support the use-mention distinction, you can look at a method `self.foo` (inspecting _its_ attributes) without actually using it `self.foo()`

**Comment by razvanc87** [comment] 2015-07-13 17:04
That makes sense. Thanks, ultimately I just wanted to understand how and why this happens.

**Comment by bfredl** [comment] 2015-07-14 11:13
Ok, closing this then.

**Closed by bfredl** 2015-07-14 11:13 UTC

**Comment by blueyed** [comment] 2018-05-01 09:25
Just for reference: https://github.com/neovim/python-client/issues/337#issuecomment-385608627 outlines a plan to fix this.
